# Generated by Django 3.2.5 on 2021-07-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210717_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='tag',
            new_name='tags',
        ),
    ]
